### PR TITLE
Introduce TravisCI

### PR DESCRIPTION
**Pull request by Naville**
You might want to change the URL and setup web-hooks yourself thought : D

### CODE REVIEW

**Comment by Razzile** [comment]
you know i've never used travis before, not really sure what i would do with this D:

**Comment by Naville** [comment]
I don't know. : ) Just integrated it into some projects and it's fucking cool.

Also, waiting for KeyStone so I can integrate it : (

**Comment by Razzile** [comment]
i'll go take a look at some travis tutorials :p

**Comment by Razzile** [comment]
I haven't forgot about this btw, I'm just waiting for exams to be over before I deal with things like this.

**Comment by Razzile** [comment]
turns out i did forget about this haha

**Pull request closed without merging**
